### ISSUE TITLE
UDP转发失败

### ISSUE THREAD

**Issue by nasaboy** [apernet/hysteria#1005]
**描述问题**
在VPS上开启warp的socks5代理，在规则里面写了命中的chatgpt网址转发给warp的socks5，但是手机上的chatgpt客户端是走的UDP，在服务器上看UDP的数据转发到warp这一段好像发生了错误

**如何复现**
复现问题的步骤。

**预期行为**
正常转发UDP数据

**日志**
```2024-03-25T09:58:01+08:00       WARN    TCP error       {"addr": "223.*.*.*:6659", "id": "user1", "reqAddr": "o4505782787964928.ingest.sentry.io:443", "error": "readfrom tcp4 172.26.3.91:37620->34.120.195.249:443: Application error 0x100 (remote)"}
2024-03-25T09:58:03+08:00       DEBUG   TCP request     {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "chat.openai.com:443"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "reqAddr": "ab.chatgpt.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "reqAddr": "ab.chatgpt.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 1, "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 1, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 1, "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 1, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "reqAddr": "ab.chatgpt.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "reqAddr": "ab.chatgpt.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 2, "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 2, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 2, "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 2, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   TCP request     {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "api.revenuecat.com:443"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 1, "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 1, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 1, "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 1, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   TCP request     {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "o33249.ingest.sentry.io:443"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "reqAddr": "ab.chatgpt.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "reqAddr": "ab.chatgpt.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 0, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 2, "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 2, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   UDP request     {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 2, "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:03+08:00       WARN    UDP error       {"addr": "223.*.*.*:6681", "id": "user1", "sessionID": 2, "error": "unexpected EOF"}
2024-03-25T09:58:03+08:00       DEBUG   TCP request     {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:03+08:00       DEBUG   TCP request     {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "ab.chatgpt.com:443"}
2024-03-25T09:58:04+08:00       DEBUG   TCP request     {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:04+08:00       DEBUG   TCP closed      {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "chat.openai.com:443"}
2024-03-25T09:58:14+08:00       DEBUG   TCP request     {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "browser-intake-datadoghq.com:443"}
2024-03-25T09:58:14+08:00       DEBUG   TCP closed      {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "browser-intake-datadoghq.com:443"}
2024-03-25T09:58:14+08:00       DEBUG   TCP closed      {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "api.revenuecat.com:443"}
2024-03-25T09:58:14+08:00       DEBUG   TCP closed      {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "ab.chatgpt.com:443"}
2024-03-25T09:58:15+08:00       DEBUG   TCP closed      {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:15+08:00       DEBUG   TCP closed      {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "o33249.ingest.sentry.io:443"}
2024-03-25T09:58:15+08:00       DEBUG   TCP closed      {"addr": "223.*.*.*:6681", "id": "user1", "reqAddr": "ios.chat.openai.com:443"}
2024-03-25T09:58:21+08:00       INFO    client disconnected     {"addr": "223.*.*.*:6658", "id": "user1"}
2024-03-25T09:58:21+08:00       DEBUG   UDP closed      {"addr": "223.*.*.*:6658", "id": "user1", "sessionID": 0}

 ```

**设备和操作系统**
hysteria v2.4.0

**额外信息**
其他你认为有助于解决问题的信息。

**Comment by haruue** [comment]
> 在VPS上开启warp的socks5代理

这个是用什么开的？

**Comment by nasaboy** [comment]
> > 在VPS上开启warp的socks5代理
> 
> 你服务器上 warp 的 socks5 服务是用什么代理软件开的？

warp自带，warp有socks代理模式

**Comment by haruue** [comment]
> warp自带，warp有socks5代理模式

经过测试， 我确信 cloudflare 官方的 warp 客户端 [warp-cli](https://developers.cloudflare.com/warp-client/get-started/linux/) 的 [proxy 模式](https://blog.cloudflare.com/announcing-warp-for-linux-and-proxy-mode) 不支持 UDP。

```
root@debian-test1:~# python3 socks5_test.py 
TCP - Sending HTTP request to 1.1.1.1
TCP test passed
Time: 6.59 ms
UDP - Sending DNS request to 1.1.1.1
Traceback (most recent call last):
  File "/root/socks5_test.py", line 50, in <module>
    test_udp()
  File "/root/socks5_test.py", line 36, in test_udp
    s.sendto(req, (TARGET, 53))
  File "/usr/lib/python3/dist-packages/socks.py", line 367, in sendto
    self.bind(("", 0))
  File "/usr/lib/python3/dist-packages/socks.py", line 353, in bind
    _, relay = self._SOCKS5_request(self._proxyconn, UDP_ASSOCIATE, dst)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/socks.py", line 533, in _SOCKS5_request
    raise SOCKS5Error("{:#04x}: {}".format(status, error))
socks.SOCKS5Error: 0x07: Command not supported, or protocol error
```

上面用到的脚本原本是用于测试 Hysteria 客户端的 socks5 的， 你可以在这里找到它： https://github.com/apernet/hysteria/blob/master/app/misc/socks5_test.py

只需将其中的 1080 （有两处）更改为 wrap-cli 的监听端口（默认是 40000）， 然后执行， 即可复现。

我也在 Cloudflare 反馈社区找到有人提了相关的问题， 但是截止目前尚未有任何回应： https://community.cloudflare.com/t/502374

**Comment by nasaboy** [comment]
好的，谢谢解答。
